version: '3.8'

services:
  todo-application:
    image: todo-application-image:latest
    ports:
      - "8082:8081"
    networks:
      - todo-network
  
  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Root@123
      - MYSQL_DATABASE=tododb
    ports:
      - "3307:3306" # Port changed from 3307 to 3308
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  mysql-data:
